import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import ElevenLabsWidget from '@/components/ElevenLabsWidget';
import WidgetErrorBoundary from '@/components/WidgetErrorBoundary';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <WidgetErrorBoundary>
          <ElevenLabsWidget agentId="agent_7701k2py9twqfw2rxfdt1z3n84m3" />
        </WidgetErrorBoundary>
        <Script
          crossOrigin="anonymous"
          integrity="sha384-lXgDNpZ7eW4rPE3gkg53l0sB+m1PmwxzgOUGSW4zkD/o71YlxacndiJgOqsUwv94"
          src="https://unpkg.com/@elevenlabs/convai-widget-embed@0.1.2"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
