import { VercelToolbar } from '@vercel/toolbar/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import FeatureFlaggedContent from '@/components/FeatureFlaggedContent';
import WidgetErrorBoundary from '@/components/WidgetErrorBoundary';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* ElevenLabs Convai Widget - positioned in bottom right */}
        <WidgetErrorBoundary>
          <div className="fixed right-4 bottom-4 z-50 h-[500px] w-[350px]">
            <FeatureFlaggedContent />
          </div>
        </WidgetErrorBoundary>

        {/* Load the ElevenLabs Convai script */}
        <Script
          src="https://elevenlabs.io/convai-widget/index.js"
          strategy="afterInteractive"
        />

        {shouldInjectToolbar && <VercelToolbar />}
      </body>
    </html>
  );
}
